"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var condicionales_1 = require("./condicionales");
var buclesFor_1 = require("./buclesFor");
var array1 = ["Casa", "Coche", "Ciudad", "Cesta"];
var array2 = ["Barco", "Baca", "Bicicleta", "Balon", "Bisiesto", "Brasil"];
var array3 = ["Venezuela", "Veneno", "Voltaje"];
var sum1 = (0, buclesFor_1.add)(array1);
console.log((0, condicionales_1.isEven)(sum1));
var sum2 = (0, buclesFor_1.add)(array2);
console.log((0, condicionales_1.isEven)(sum2));
var sum3 = (0, buclesFor_1.add)(array3);
console.log((0, condicionales_1.isEven)(sum3));
